name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: 'script -q -e -c "bash {0}"'
    env:
      CPPFLAGS: -Wno-unknown-pragmas -Wno-unused-but-set-variable -Wno-unused-function
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Caching time
      uses: actions/cache@v2.1.6
      id: caching-time
      with:
        path: |
          flatbuffers/
          /home/runner/.cache/pip
        key: wheeeeeeeeeeeeeeeee

    - name: Clone/Build Flatbuffers
      if: steps.caching-time.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/StardustXR/libstardustxr.git
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers/
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DFLATBUFFERS_BUILD_TESTS=OFF -DFLATBUFFERS_BUILD_FLATC=OFF -DFLATBUFFERS_BUILD_FLATHASH=OFF -DFLATBUFFERS_BUILD_SHAREDLIB=ON -DCMAKE_INSTALL_PREFIX=/usr
        make -j2
    - name: Install Flatbuffers
      run: |
        cd flatbuffers/
        sudo make install
    
    - name: Build libstardustxr
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: libstardustxr build
        meson-version: 0.53.0
        options: -j2
    
    - name: Build Server
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: build
        meson-version: 0.53.0
        options: -j2
